package ec.edu.espe.restaurant.view;

import com.toedter.calendar.JDateChooser;
import ec.edu.espe.restaurant.controller.CustomerController;
import ec.edu.espe.restaurant.controller.ServiceController;
import ec.edu.espe.restaurant.model.MongoDBConnection;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author GiftSoft TEAM, DCCO-ESPE
 */

public class PanelRegisterOrder extends javax.swing.JPanel {


    public PanelRegisterOrder() {
        initComponents();
        MongoDBConnection mongoDB;
        mongoDB = new MongoDBConnection();
        mongoDB.connectDatabase();
    }
    
SimpleDateFormat formDate = new SimpleDateFormat("dd-MM-yy");
    
    public String getDate(JDateChooser jdDate){
        if(jdDate.getDate() != null){
            return formDate.format(jdDate.getDate());
        } 
        else{
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDataCustomer = new javax.swing.JLabel();
        lblSN = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblCEllphone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTOS = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFN1 = new javax.swing.JLabel();
        txt_Surnames = new javax.swing.JTextField();
        txt_FullNames = new javax.swing.JTextField();
        txt_Id = new javax.swing.JTextField();
        txt_Cellphone = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Cost = new javax.swing.JTextField();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        btn_Register = new javax.swing.JButton();
        btn_NewRegister = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calendarDate = new com.toedter.calendar.JDateChooser();
        txt_Hour = new javax.swing.JFormattedTextField();
        btn_Register1 = new javax.swing.JButton();
        cmb_Food = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        BtnInvoice = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(740, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDataCustomer.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        lbDataCustomer.setText("REGISTER");
        jPanel1.add(lbDataCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, -1));

        lblSN.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblSN.setText("Last Names:");
        jPanel1.add(lblSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        lblId.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblId.setText("ID:");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 30, -1));

        lblCEllphone.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblCEllphone.setText("Cellphone:");
        jPanel1.add(lblCEllphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblEmail.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblEmail.setText("Email:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lblTOS.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblTOS.setText("Food");
        jPanel1.add(lblTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, 20));

        lblCost.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblCost.setText("Cost $ :");
        jPanel1.add(lblCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Payment Method:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        lblFN1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblFN1.setText("Full Names:");
        jPanel1.add(lblFN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txt_Surnames.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Surnames.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SurnamesKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Surnames, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, 30));

        txt_FullNames.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_FullNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FullNamesActionPerformed(evt);
            }
        });
        txt_FullNames.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FullNamesKeyTyped(evt);
            }
        });
        jPanel1.add(txt_FullNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 250, 30));

        txt_Id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_IdKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 210, 30));

        txt_Cellphone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Cellphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CellphoneKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Cellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 210, 30));

        txt_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 250, 30));

        txt_Cost.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CostKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 110, 30));

        cmbPaymentMethod.setBackground(new java.awt.Color(204, 153, 255));
        cmbPaymentMethod.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta de Credito", "Tarjeta de Debito ", "PayPal" }));
        cmbPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaymentMethodActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 170, 30));

        btn_Register.setBackground(new java.awt.Color(204, 153, 255));
        btn_Register.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_Register.setText("REGISTER");
        btn_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_RegisterMouseExited(evt);
            }
        });
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 150, 40));

        btn_NewRegister.setBackground(new java.awt.Color(204, 153, 255));
        btn_NewRegister.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_NewRegister.setText("NEW REGISTER");
        btn_NewRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_NewRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_NewRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_NewRegisterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_NewRegisterMousePressed(evt);
            }
        });
        btn_NewRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_NewRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 160, 30));

        btn_Cancel.setBackground(new java.awt.Color(204, 153, 255));
        btn_Cancel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_Cancel.setText("CANCEL");
        btn_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CancelMousePressed(evt);
            }
        });
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Date:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 70, 20));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Hour of attention:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 210, 20));
        jPanel1.add(calendarDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 230, 30));

        try {
            txt_Hour.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_Hour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HourActionPerformed(evt);
            }
        });
        txt_Hour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_HourKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_HourKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 50, 30));

        btn_Register1.setBackground(new java.awt.Color(0, 255, 204));
        btn_Register1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Register1.setText("REGISTER");
        btn_Register1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Register1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, -1));

        cmb_Food.setBackground(new java.awt.Color(204, 153, 255));
        cmb_Food.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        cmb_Food.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lasagna de Pollo", "Lasagna de Carne", "Milanesa", "Rabioles de ricotta", "Tortellini de jamon", "Sorrentino de pollo", "Stroganoof (mar y tierra)", "Pizza Hawaiana", "Pizza Vegetariana", "Pizza peperoni", "Pizza jamon", "Pizza napolitana", "Panini de pollo", "Panini de lomo", "Panini napolitano" }));
        jPanel1.add(cmb_Food, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 190, 30));

        jPanel4.setBackground(new java.awt.Color(204, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        BtnInvoice.setBackground(new java.awt.Color(255, 102, 255));
        BtnInvoice.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        BtnInvoice.setText("INVOICE");
        BtnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(BtnInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 120, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
    CustomerController customerController;
    customerController = new CustomerController("Orders");
        
    int i =  JOptionPane.showConfirmDialog(this,"Register Order?","Aviso",JOptionPane.WARNING_MESSAGE);
        
      if(i==0){
        customerController.createToDatabase(customerController.RegisterAndBuildDocument(txt_FullNames.getText(), 
                txt_Surnames.getText(),
                txt_Id.getText(),
                txt_Cellphone.getText(),
                txt_Email.getText(), 
                cmb_Food.getSelectedItem().toString(), 
                txt_Cost.getText(), 
                cmbPaymentMethod.getSelectedItem().toString(), 
                formDate.format(calendarDate.getDate()), 
                txt_Hour.getText()));

        JOptionPane.showMessageDialog(this, "Data saved successfully");
      }else if(i==1){
          this.setVisible(true);
      }
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void txt_FullNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FullNamesActionPerformed
        //
    }//GEN-LAST:event_txt_FullNamesActionPerformed

    private void txt_FullNamesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FullNamesKeyTyped
        
        char validateLetters = evt.getKeyChar();
        if(Character.isDigit(validateLetters)){
        evt.consume();
        JOptionPane.showMessageDialog(txt_FullNames, "Enter only letters","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_FullNamesKeyTyped

    private void txt_CellphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CellphoneKeyPressed
        
        String value = txt_Cellphone.getText();
        int legth = value.length(); 
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            txt_Cellphone.setEditable(true);
            if(legth>=10){             
                JOptionPane.showMessageDialog(this, "Cellphone number must have 10 digits","Warning",JOptionPane.WARNING_MESSAGE);
                txt_Cellphone.setText("");                
            }
        }else {
            JOptionPane.showMessageDialog(this, "Enter only numbers","Warning",JOptionPane.WARNING_MESSAGE);
                txt_Cellphone.setText("");
        }
    }//GEN-LAST:event_txt_CellphoneKeyPressed

    private void txt_IdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdKeyPressed
        String value = txt_Id.getText();
        int legth = value.length();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            txt_Id.setEditable(true);
            if(legth>=10){              
                JOptionPane.showMessageDialog(this, "ID must have 10 digits","Warning",JOptionPane.WARNING_MESSAGE);
                txt_Id.setText("");               
            }
        }else {
            JOptionPane.showMessageDialog(this, "Enter only numbers","Warning",JOptionPane.WARNING_MESSAGE);
                txt_Id.setText("");
        }
    }//GEN-LAST:event_txt_IdKeyPressed

    private void btn_Register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Register1ActionPerformed

    }//GEN-LAST:event_btn_Register1ActionPerformed

    private void btn_NewRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewRegisterActionPerformed
        
      int i =  JOptionPane.showConfirmDialog(this,"Register a new Order?","Warning",JOptionPane.WARNING_MESSAGE);
        
      if(i==0){
        txt_FullNames.setText("");
        txt_Surnames.setText("");
        txt_Id.setText("");
        txt_Cellphone.setText("");
        txt_Email.setText("");
        txt_Cost.setText("");
        txt_Hour.setText("");
      }else if(i==1){
          this.setVisible(true);
      }
    }//GEN-LAST:event_btn_NewRegisterActionPerformed

    private void btn_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseEntered

    }//GEN-LAST:event_btn_CancelMouseEntered

    private void btn_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseExited
        
    }//GEN-LAST:event_btn_CancelMouseExited

    private void btn_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegisterMouseEntered
       
    }//GEN-LAST:event_btn_RegisterMouseEntered

    private void btn_RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegisterMouseExited
        
    }//GEN-LAST:event_btn_RegisterMouseExited

    private void btn_NewRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewRegisterMouseEntered
        
    }//GEN-LAST:event_btn_NewRegisterMouseEntered

    private void btn_NewRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewRegisterMouseExited
       
    }//GEN-LAST:event_btn_NewRegisterMouseExited

    private void btn_CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMousePressed
        int i =  JOptionPane.showConfirmDialog(this,"Do you want cancel? you don't save data","Warning",JOptionPane.WARNING_MESSAGE);
        if(i==0){
        txt_FullNames.setText("");
        txt_Surnames.setText("");
        txt_Id.setText("");
        txt_Cellphone.setText("");
        txt_Email.setText("");
        txt_Cost.setText("");
        txt_Hour.setText("");
        }else if(i==1){
            this.setVisible(true);
        }
    }//GEN-LAST:event_btn_CancelMousePressed

    private void txt_HourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HourActionPerformed

    }//GEN-LAST:event_txt_HourActionPerformed

    private void txt_HourKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HourKeyPressed
        ServiceController h;
        h = new ServiceController();
        if(h.Validar_CampoHora(txt_Hour.getText())== false){
         
        }
    }//GEN-LAST:event_txt_HourKeyPressed

    private void txt_HourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HourKeyTyped
    
    }//GEN-LAST:event_txt_HourKeyTyped

    private void txt_SurnamesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SurnamesKeyTyped

        char validateLetters = evt.getKeyChar();
        if(Character.isDigit(validateLetters)){
        evt.consume();
        JOptionPane.showMessageDialog(txt_Surnames, "Enter only letters","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_SurnamesKeyTyped

    private void txt_CostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CostKeyTyped
        char character = evt.getKeyChar();
        
        if(((character < '0' || character > '9')) && (character != KeyEvent.VK_BACK_SPACE)
            && (character != '.' || txt_Cost.getText().contains(".") )){
            evt.consume();
        }
    }//GEN-LAST:event_txt_CostKeyTyped

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        //
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_NewRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewRegisterMousePressed
        int i =  JOptionPane.showConfirmDialog(this,"Register a new order?","Aviso",JOptionPane.WARNING_MESSAGE);
        if(i==0){
        txt_FullNames.setText("");
        txt_Surnames.setText("");
        txt_Id.setText("");
        txt_Cellphone.setText("");
        txt_Email.setText("");
        txt_Cost.setText("");
        txt_Hour.setText("");
        }else if(i==1){
            this.setVisible(true);
        }
    }//GEN-LAST:event_btn_NewRegisterMousePressed

    private void cmbPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentMethodActionPerformed

    }//GEN-LAST:event_cmbPaymentMethodActionPerformed

    private void BtnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvoiceActionPerformed
        FrmInvoice FrmInvoice = new FrmInvoice();
        this.setVisible(false);
        FrmInvoice.setVisible(true); 
    }//GEN-LAST:event_BtnInvoiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInvoice;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_NewRegister;
    private javax.swing.JButton btn_Register;
    private javax.swing.JButton btn_Register1;
    private com.toedter.calendar.JDateChooser calendarDate;
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JComboBox<String> cmb_Food;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbDataCustomer;
    private javax.swing.JLabel lblCEllphone;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFN1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblSN;
    private javax.swing.JLabel lblTOS;
    private javax.swing.JTextField txt_Cellphone;
    private javax.swing.JTextField txt_Cost;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FullNames;
    private javax.swing.JFormattedTextField txt_Hour;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Surnames;
    // End of variables declaration//GEN-END:variables
}
